import os
pj = os.path.join

Import('GetPlatform', 'optimize')

builddir = 'build.' + GetPlatform()
if optimize != 'no':
   builddir = builddir + '.opt'
BuildDir(builddir, 'TestSuite', duplicate=0)

SConscript(dirs = builddir)
