import os
pj = os.path.join

sources = Split("""
   AABoxContainTest
   AABoxOpsTest
   AABoxTest
   AxisAngleClassTest
   AxisAngleCompareTest
   ConvertTest
   CoordClassTest
   CoordCompareTest
   TriTest
   SphereTest
""")

#sources = Split("""
#   CoordGenTest
#   EulerAngleClassTest
#   EulerAngleCompareTest
#   IntersectionTest
#   LineSegTest
#   MatrixClassTest
#   MatrixCompareTest
#   MatrixGenTest
#   MatrixOpsTest
#   OutputTest
#   PlaneTest
#   PointTest
#   QuatClassTest
#   QuatCompareTest
#   QuatGenTest
#   QuatOpsTest
#   QuatStuffTest
#   VecBaseTest
#   VecGenTest
#   VecTest
#   XformTest
#""")

sources = map(lambda n: n + '.cpp', sources)

# Get sources in the InfoTests dir
#infotests_sources = SConscript(dirs = 'InfoTests')
#infotests_sources = map(lambda n: pj('InfoTests', n), infotests_sources)
#sources.extend(infotests_sources)

Return('sources')
