import os
pj = os.path.join

Import('pkg baseEnv PREFIX')

headers = Split("""
   gmtl-Containment.h
   gmtl-GenOps.h
   gmtl-Generate.h
   gmtl-LineSegOps.h
   gmtl-MatrixOps.h
   gmtl-PlaneOps.h
   gmtl-QuatOps.h
   gmtl-TriOps.h
   gmtl-VecOps.h
   gmtl-Xforms.h
   gmtl-functions.h
   gmtl-getData-wrappers.h
   gmtl-intersect-wrappers.h
   gmtl-wrappers.h
""")

subdirs = Split("""
   gmtl
""")

for s in subdirs:
   SConscript(dirs = s)

for h in headers:
   baseEnv.Install(pj(PREFIX, 'python', 'src'), h)
   pkg.addExtraDist([File(h)])

