import os
pj = os.path.join

Import('pkg baseEnv PREFIX')

cpp_files = Split("""
   _AABox_double.cpp
   _AABox_float.cpp
   _AxisAngle_double.cpp
   _AxisAngle_float.cpp
   _Coord_gmtl_Vec_double_3_gmtl_AxisAngle_double.cpp
   _Coord_gmtl_Vec_double_3_gmtl_EulerAngle_double_gmtl_XYZ.cpp
   _Coord_gmtl_Vec_double_3_gmtl_EulerAngle_double_gmtl_ZXY.cpp
   _Coord_gmtl_Vec_double_3_gmtl_EulerAngle_double_gmtl_ZYX.cpp
   _Coord_gmtl_Vec_double_3_gmtl_Quat_double.cpp
   _Coord_gmtl_Vec_double_4_gmtl_AxisAngle_double.cpp
   _Coord_gmtl_Vec_double_4_gmtl_EulerAngle_double_gmtl_XYZ.cpp
   _Coord_gmtl_Vec_double_4_gmtl_EulerAngle_double_gmtl_ZXY.cpp
   _Coord_gmtl_Vec_double_4_gmtl_EulerAngle_double_gmtl_ZYX.cpp
   _Coord_gmtl_Vec_double_4_gmtl_Quat_double.cpp
   _Coord_gmtl_Vec_float_3_gmtl_AxisAngle_float.cpp
   _Coord_gmtl_Vec_float_3_gmtl_EulerAngle_float_gmtl_XYZ.cpp
   _Coord_gmtl_Vec_float_3_gmtl_EulerAngle_float_gmtl_ZXY.cpp
   _Coord_gmtl_Vec_float_3_gmtl_EulerAngle_float_gmtl_ZYX.cpp
   _Coord_gmtl_Vec_float_3_gmtl_Quat_float.cpp
   _Coord_gmtl_Vec_float_4_gmtl_AxisAngle_float.cpp
   _Coord_gmtl_Vec_float_4_gmtl_EulerAngle_float_gmtl_XYZ.cpp
   _Coord_gmtl_Vec_float_4_gmtl_EulerAngle_float_gmtl_ZXY.cpp
   _Coord_gmtl_Vec_float_4_gmtl_EulerAngle_float_gmtl_ZYX.cpp
   _Coord_gmtl_Vec_float_4_gmtl_Quat_float.cpp
   _EulerAngle_float_gmtl_XYZ.cpp
   _EulerAngle_float_gmtl_ZXY.cpp
   _EulerAngle_float_gmtl_ZYX.cpp
   _LineSeg_double.cpp
   _LineSeg_float.cpp
   _Matrix_float_3_3.cpp
   _Matrix_float_4_4.cpp
   _Plane_double.cpp
   _Plane_float.cpp
   _Point_float_2.cpp
   _Point_float_3.cpp
   _Point_int_2.cpp
   _Point_int_3.cpp
   _Quat_double.cpp
   _Quat_float.cpp
   _Ray_double.cpp
   _Ray_float.cpp
   _Sphere_double.cpp
   _Sphere_float.cpp
   _Tri_double.cpp
   _Tri_float.cpp
   _Tri_int.cpp
   _VecBase_double_2.cpp
   _VecBase_double_3.cpp
   _VecBase_double_4.cpp
   _VecBase_float_2.cpp
   _VecBase_float_3.cpp
   _VecBase_float_4.cpp
   _VecBase_int_2.cpp
   _VecBase_int_3.cpp
   _VecBase_int_4.cpp
   _Vec_double_3.cpp
   _Vec_double_4.cpp
   _Vec_float_3.cpp
   _Vec_float_4.cpp
   _Vec_int_3.cpp
   _Vec_int_4.cpp
   _gmtl_AABoxOps_h.cpp
   _gmtl_AxisAngleOps_h.cpp
   _gmtl_Containment_h.cpp
   _gmtl_CoordOps_h.cpp
   _gmtl_Defines_h.cpp
   _gmtl_EulerAngleOps_h.cpp
   _gmtl_Generate_h.cpp
   _gmtl_LineSegOps_h.cpp
   _gmtl_Math_h.cpp
   _gmtl_MatrixOps_h.cpp
   _gmtl_PlaneOps_h.cpp
   _gmtl_QuatOps_h.cpp
   _gmtl_SphereOps_h.cpp
   _gmtl_TriOps_h.cpp
   _gmtl_VecOps_h.cpp
   _gmtl_Xforms_h.cpp
   _gmtl_intersect_wrappers_h.cpp
   _gmtl_wrappers_h.cpp
   gmtl.cpp
""")

for f in cpp_files:
   baseEnv.Install(pj(PREFIX, 'python', 'src', 'gmtl'), f)
   pkg.addExtraDist([File(f)])

