import os
pj = os.path.join

Import('pkg baseEnv PREFIX')

headers = Split("""
   Assert
   Meta
   StaticAssert
""")

headers = map(lambda n: n + '.h', headers)

for h in headers:
   baseEnv.Install(pj(PREFIX, 'include', 'gmtl', 'Util'), h)
   pkg.addExtraDist([h])
