import glob
import os
pj = os.path.join

Import('baseEnv optimize pkg')
Import('GetPlatform ApplyBoostOptions ApplyPythonOptions')


subdirs = Split("""
   pyste
   src
   test
""")

for s in subdirs:
   SConscript(dirs = s)

sources = glob.glob(pj(str(Dir('#python/src/gmtl')), '*.cpp'))
sources = map(lambda n: pj('src', 'gmtl', os.path.basename(n)), sources)


# Define the Python module
env = baseEnv.Copy()

# If on linux deal with ld O(n^2) algorithm
if(GetPlatform() == "linux"):
   env['CXXCOM'] += " ; objcopy --set-section-flags .debug_str=contents,debug $TARGET"
   env['SHCXXCOM'] += " ; objcopy -v --set-section-flags .debug_str=contents,debug $TARGET $TARGET"
ApplyBoostOptions(env)
ApplyPythonOptions(env)
env.Append(CPPPATH   = ['#', '#python/src'])

python_module = 'gmtl'

# On Windows, it seems that a debug build of Python prefers that the modules
# have file names that end in _d.
if GetPlatform() == 'win32' and optimize != 'yes':
   python_module += '_d'

env.SharedLibrary(python_module, sources, SHLIBPREFIX='')
