import glob
import os
pj = os.path.join

Import('baseEnv pkg')
Import('ApplyBoostOptions ApplyPythonOptions')


subdirs = Split("""
   pyste
   src
   test
""")

for s in subdirs:
   SConscript(dirs = s)

sources = glob.glob(pj(str(Dir('#python/src/gmtl')), '*.cpp'))
sources = map(lambda n: pj('src', 'gmtl', os.path.basename(n)), sources)


# Define the Python module
env = baseEnv.Copy()
ApplyBoostOptions(env)
ApplyPythonOptions(env)
env.Append(CPPPATH   = ['#', '#python/src'])
env.SharedLibrary('gmtl', sources, SHLIBPREFIX='')
