import glob
import os
pj = os.path.join

Import('baseEnv pkg')
Import('SetupPython SetupBoostPython')

sources = glob.glob(pj(str(Dir('#python/src/gmtl')), '*.cpp'))
sources = map(lambda n: pj('src', 'gmtl', os.path.basename(n)), sources)


# Define the Python module
env = baseEnv.Copy()
env.Append(CPPPATH   = ['#', '#python/src'])
SetupPython(env, 2.2)
SetupBoostPython(env)
env.SharedLibrary('gmtl', sources, SHLIBPREFIX='')
