import os
pj = os.path.join

Import('pkg baseEnv PREFIX installed_targets')

# XXX: Can't this be constructed automatically by scanning?  -PH 9/19/2004
headers = Split("""
   AABox
   AABoxOps
   AxisAngle
   AxisAngleOps
   Comparitors
   Config
   Containment
   Coord
   CoordOps
   Defines
   EulerAngle
   EulerAngleOps
   Generate
   gmtl
   Helpers
   Intersection
   LineSeg
   LineSegOps
   Math
   Matrix
   MatrixOps
   Output
   Plane
   PlaneOps
   Point
   Quat
   QuatOps
   Ray
   RayOps
   Sphere
   SphereOps
   Tri
   TriOps
   Vec
   VecBase
   VecExprMeta
   VecOps
   VecOpsMeta
   Version
   Xforms
""")

headers = map(lambda n: n + '.h', headers)

subdirs = Split("""
   External
   Util
""")

for s in subdirs:
   SConscript(dirs = s)

for h in headers:
   installed_targets += baseEnv.Install(pj(PREFIX, 'include', 'gmtl'), h)
   pkg.addExtraDist([File(h)])
